---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "webapp.name" . }}-service
  labels:
    app: {{ include "webapp.name" . }}-service
  namespace: {{ .Release.Namespace }}
spec:
  {{ if .Values.service }}
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: {{ .Values.service.name }}
  {{ end }}
  selector:
    {{ include "webapp.selectorLabels" . | nindent 4 }}